### ISSUE TITLE
Neo4j “Username is not supported in the URI” error - Parsing a local Repo

### ISSUE THREAD

**Issue by galsi** [potpie-ai/potpie#403]
Hi 
I am running latest version on local Linux and get the following error 
The exact error message (neo4j.exceptions.ConfigurationError: Username is not supported in the URI).

The Command  : 
```
 curl -X POST 'http://localhost:8001/api/v1/parse' -H "Content-Type: application/json" -d '{"repo_path":"/home/ubgals/repos/potpie/projects/claude-task-master","branch_name":"main"}'

Internal Server Error
```

Full Log
```
|   File "/usr/local/lib/python3.10/site-packages/neo4j/api.py", line 551, in parse_neo4j_uri
potpie_backend  |     raise ConfigurationError("Username is not supported in the URI")
potpie_backend  | neo4j.exceptions.ConfigurationError: Username is not supported in the URI
potpie_backend  |     return await func(*args, **kwargs)
potpie_backend  |   File "/app/app/modules/parsing/graph_construction/parsing_controller.py", line 49, in parse_directory
potpie_backend  |     parsing_service = ParsingService(db, user_id)
potpie_backend  |   File "/app/app/modules/parsing/graph_construction/parsing_service.py", line 40, in __init__
potpie_backend  |     self.inference_service = InferenceService(db, user_id)
potpie_backend  |   File "/app/app/modules/parsing/knowledge_graph/inference_service.py", line 29, in __init__
potpie_backend  |     self.driver = GraphDatabase.driver(
potpie_backend  |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 202, in driver
potpie_backend  |     driver_type, security_type, parsed = parse_neo4j_uri(uri)
potpie_backend  |   File "/usr/local/lib/python3.10/site-packages/neo4j/api.py", line 551, in parse_neo4j_uri
potpie_backend  |     raise ConfigurationError("Username is not supported in the URI")
potpie_backend  | neo4j.exceptions.ConfigurationError: Username is not supported in the URI
```

Here is  my potpie-backend 
```
  potpie-backend:
    build: .
    container_name: potpie_backend
    depends_on:
      - postgres
      - redis
      - neo4j
    env_file:
      - .env
    environment:
      ENV: development
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      OPENAI_DEPLOYMENT_NAME: ${OPENAI_DEPLOYMENT_NAME}
      POSTGRES_SERVER: postgresql://postgres:mysecretpassword@postgres:5432/momentum
      # Neo4j configuration: URI without credentials, credentials provided separately
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: mysecretpassword
      REDISHOST: redis
      REDISPORT: 6379
      BROKER_URL: redis://redis:6379/0
      PROJECT_PATH: /app/projects
    ports:
      - "8001:8000"
    volumes:
      - ./projects:/app/projects
    networks:
      - app-network
```

My Docker 

```
CONTAINER ID   IMAGE                    STATUS                    PORTS
1159ed495e16   potpie-potpie-frontend   Up 54 minutes             0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp
40306a655fc3   potpie-potpie-backend    Up 54 minutes             0.0.0.0:8001->8000/tcp, [::]:8001->8000/tcp
2a33679a6885   postgres:latest          Up 54 minutes (healthy)   0.0.0.0:5432->5432/tcp, [::]:5432->5432/tcp
c55a723bc1f3   neo4j:latest             Up 54 minutes             0.0.0.0:7474->7474/tcp, [::]:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp, [::]:7687->7687/tcp
7eca07b0d244   redis:latest             Up 54 minutes             0.0.0.0:6379->6379/tcp, [::]:6379->6379/tcp

```

Please Advise

**Comment by dhirenmathur** [comment]
@nndn can you check this out

**Comment by nndn** [comment]
@galsi i think the key for env variables is wrong.

NEO4J_URI=bolt://127.0.0.1:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=mysecretpassword

shoud be something like this. NEO4J_USER => NEO4J_USERNAME

**Comment by galsi** [comment]
thanks - fixed the problem - attached full dection
```
  potpie-backend:
    build: .
    container_name: potpie_backend
    depends_on:
      - postgres
      - redis
      - neo4j
    env_file:
      - .env
    environment:
      ENV: development
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      OPENAI_DEPLOYMENT_NAME: ${OPENAI_DEPLOYMENT_NAME}
      POSTGRES_SERVER: postgresql://postgres:mysecretpassword@postgres:5432/momentum
      # Neo4j configuration: URI without credentials, credentials provided separately
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      REDISHOST: redis
      REDISPORT: 6379
      BROKER_URL: redis://redis:6379/0
      PROJECT_PATH: /app/projects
    ports:
      - "8001:8000"
    volumes:
      - ./projects:/app/projects
    networks:
      - app-network
```
